spring:
  application:
    name: microservice-consumer-movie-ribbon-without-eureka
server:
  port: 8082
#user:
#  userServerPath: http://localhost:8080/simple/
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
 #   instance-id: ${spring.application.name}:${spring.application.name}:${server.port}
microservice-privider-user:
  ribbon:
    listOfServers: localhost:8080