server:
  port: 8080
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springCloud?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  application:
    name: microservice-privider-user
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.fu: debug
  file: logs/mylog.log
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.name}:${server.port}
management:
#  port: 8888
  security:
    enabled: false   